name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-code:
    name: Prettier, ESLint, and TypeScript Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run Prettier
        run: npx prettier . --check

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript Check
        run: npm run typecheck

  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Create .env file
        run: |
          echo "AWS_ACCESS_KEY_ID=XXXXXXXX" >> .env
          echo "AWS_SECRET_ACCESS_KEY=XXXXXXXX" >> .env
          echo "AWS_REGION=us-east-1" >> .env
          echo "AWS_SNS_TOPIC_ARN=arn:aws:sns:us-east-1:XXXXXXXX:aws-sns-topic" >> .env
          echo "SNS_TOPIC_NAME=aws-sns-topic" >> .env
          echo "EMAIL_ADDRESS=example@example.com" >> .env

      - name: Run Jest tests
        run: npm run test:coverage
